M48
; DRILL file {KiCad 7.0.7} date Fri Oct 20 13:37:22 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-10-20T13:37:22-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C5.000
%
G90
G05
T1
X41.941Y-29.622
X41.941Y-188.818
X145.003Y-29.622
X145.003Y-188.818
T0
M30
